In [5]:
import tensorflow as tf
import pandas as pd
import numpy as np
import os
import pickle
from sklearn.metrics import  precision_recall_fscore_support, balanced_accuracy_score, matthews_corrcoef
# from modelValidation import calculate_results
# "C:\Users\edoar\Desktop\Modeling2.0\BestModels_AI_10_ottobre\DataPrefetch"

# FOLDER_NAME = "BestModels_AI_90_10"
path = os.getcwd()
# path = os.path.join(path, FOLDER_NAME)
MODEL_FOLDER = os.path.join(path, 'Models')

In [6]:
def calculate_results(y_true, y_pred):
    """
    Calculates model accuracy, precision, recall and f1 score of a binary classification model.
    Args:
      y_true: true labels in the form of a 1D array
      y_pred: predicted labels in the form of a 1D array
    Returns a dictionary of accuracy, precision, recall, f1-score.
    """
    # Calculate model accuracy
    # model_accuracy = accuracy_score(y_true, y_pred)
    model_balance_accuracy = balanced_accuracy_score(y_true, y_pred)
    # model_recall = recall_score(y_true, y_pred, pos_label=1)
    specificity = fn_specificty(y_true, y_pred)
    mcc = matthews_corrcoef(y_true, y_pred)
    # sensitivity = fn_sensitivity(y_true, y_pred)
    # f1_score = fn_F1score(y_true, y_pred)
    # Calculate model precision, recall and f1 score using "weighted average
    model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, pos_label=1, average="binary") # "weighted"
    model_results = {"Balance Accuracy": model_balance_accuracy,
                   "Precision": model_precision,
                   "Sensitivity": model_recall,
                   "Specificity": specificity,
                   "MCC": mcc,
                   "f1": model_f1}
    return model_results

## Import model

In [18]:
path = os.path.join(os.getcwd(), "charsEmbeddingAugemted_90_10")
path_model = os.path.join(path, "Model_charsEmbeddingAugemted")
path_test_set = os.path.join(path, "test_charsEmbeddingAugemted_dataset")

In [20]:
test_set = tf.data.Dataset.load(path_test_set)
new_model = tf.keras.models.load_model(path_model)

In [42]:
os.listdir(os.getcwd())

['.ipynb_checkpoints',
 'charsEmbeddingAugemted_90_10',
 'DataAnalysis_on_models_performance.ipynb',
 'Models']

In [27]:
next(iter(test_set))[0]

<tf.Tensor: shape=(32,), dtype=string, numpy=
array([b'C C C C n 1 c c [ n + ] ( C ) c 1',
       b'C C ( C C c 1 c c c c c 1 ) N C C ( O ) c 1 c c c ( O ) c ( C ( N ) = O ) c 1',
       b'C C C ( C c 1 c ( I ) c c ( I ) c ( N ) c 1 I ) C ( = O ) O',
       b'C c 1 c c ( - c 2 c c c ( N ) c ( C ) c 2 ) c c c 1 N',
       b'N S ( = O ) ( = O ) c 1 c c c c c 1 C l',
       b'C C C C C ( C C ) C O C ( = O ) c 1 c c c c c 1 C ( = O ) O',
       b'C C N ( C C C # N ) c 1 c c c c c 1',
       b'C C C O c 1 n n ( C ( = O ) N S ( = O ) ( = O ) c 2 c c c c c 2 C ( = O ) O C ) c ( = O ) n 1 C',
       b'C C 1 2 C C C 3 C ( C C C 4 C C ( = O ) C C C 4 3 C ) C 1 C C C 2 O',
       b'C C C C C ( C C ) C O C ( = O ) C O c 1 c c c ( C l ) c c 1 C',
       b'C C C C C c 1 c c c ( N ) c c 1',
       b'C = C C ( = O ) N 1 C C O C C 1',
       b'C C ( O c 1 c c c ( C N C ( = O ) c 2 c c c n c 2 O c 2 c c c 3 c ( c 2 ) O C O 3 ) c ( F ) c 1 ) C ( = O ) O',
       b'C c 1 c c c ( C l ) c c 1 N',
       b'N

In [17]:
new_model.summary()

Model: "charsEmbeddingAugemted"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 inputs_smiles_as_char (Inpu  [(None, 1)]              0         
 tLayer)                                                         
                                                                 
 char_vectorizer (TextVector  (None, 117)              0         
 ization)                                                        
                                                                 
 char_embed (Embedding)      (None, 117, 264)          7392      
                                                                 
 conv1d_2 (Conv1D)           (None, 117, 128)          169088    
                                                                 
 conv1d_3 (Conv1D)           (None, 117, 64)           41024     
                                                                 
 bidirectional_2 (Bidirectio  (None, 117, 12

In [34]:
def prepare_smiles_NLP(text): 
    smi = " ".join(list(text))
    return tf.expand_dims(tf.constant(smi, dtype=tf.string), axis=0)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'c c c c c c O'], dtype=object)>

In [35]:
new_model.predict(smiles)

1/1 [==============================] - 3s 3s/step


array([[0.19017208]], dtype=float32)

In [41]:
pred = (new_model.predict(smiles).squeeze() > 0.5).astype(int)
pred

1/1 [==============================] - 0s 30ms/step


0

### Import Multimodal

In [66]:
path = os.path.join(os.getcwd(), "MultimodalModels_all")
path_model = os.path.join(path, "Model_multimodal_all")
path_test_set = os.path.join(path, "test_MultimodalModels_all_dataset")

In [67]:
test_set = tf.data.Dataset.load(path_test_set)
multimodal = tf.keras.models.load_model(path_model)

In [68]:
multimodal.summary()

Model: "model_5"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 inputs_smiles_as_char (InputLa  [(None, 1)]         0           []                               
 yer)                                                                                             
                                                                                                  
 char_vectorizer (TextVectoriza  (None, 111)         0           ['inputs_smiles_as_char[0][0]']  
 tion)                                                                                            
                                                                                                  
 char_embed (Embedding)         (None, 111, 264)     7392        ['char_vectorizer[0][0]']        
                                                                                            

 batch_normalization_17 (BatchN  (None, 64)          256         ['dense_39[0][0]']               
 ormalization)                                                                                    
                                                                                                  
 batch_normalization_19 (BatchN  (None, 64)          256         ['dense_42[0][0]']               
 ormalization)                                                                                    
                                                                                                  
 batch_normalization_21 (BatchN  (None, 64)          256         ['dense_45[0][0]']               
 ormalization)                                                                                    
                                                                                                  
 dropout_22 (Dropout)           (None, 32)           0           ['batch_normalization_13[0][0]'] 
          

In [52]:
import deepchem as dc

In [62]:
def fingerprint_cfp(smiles):
    featurizer = dc.feat.CircularFingerprint(size=1024, radius=4)    
    return [int(i) for i in featurizer.featurize(smiles).tolist()[0]]

def create_MACCs_fingerprint_frame(smiles):
    featurizer = dc.feat.MACCSKeysFingerprint()
    return featurizer.featurize(smiles).tolist()[0] 

In [71]:
type(next(iter(test_set)))

tuple

In [72]:
next(iter(test_set))

((<tf.Tensor: shape=(32,), dtype=string, numpy=
  array([b'C C C C n 1 c c [ n + ] ( C ) c 1',
         b'C C ( C C c 1 c c c c c 1 ) N C C ( O ) c 1 c c c ( O ) c ( C ( N ) = O ) c 1',
         b'C C C ( C c 1 c ( I ) c c ( I ) c ( N ) c 1 I ) C ( = O ) O',
         b'C c 1 c c ( - c 2 c c c ( N ) c ( C ) c 2 ) c c c 1 N',
         b'N S ( = O ) ( = O ) c 1 c c c c c 1 C l',
         b'C C C C C ( C C ) C O C ( = O ) c 1 c c c c c 1 C ( = O ) O',
         b'C C N ( C C C # N ) c 1 c c c c c 1',
         b'C C C O c 1 n n ( C ( = O ) N S ( = O ) ( = O ) c 2 c c c c c 2 C ( = O ) O C ) c ( = O ) n 1 C',
         b'C C 1 2 C C C 3 C ( C C C 4 C C ( = O ) C C C 4 3 C ) C 1 C C C 2 O',
         b'C C C C C ( C C ) C O C ( = O ) C O c 1 c c c ( C l ) c c 1 C',
         b'C C C C C c 1 c c c ( N ) c c 1',
         b'C = C C ( = O ) N 1 C C O C C 1',
         b'C C ( O c 1 c c c ( C N C ( = O ) c 2 c c c n c 2 O c 2 c c c 3 c ( c 2 ) O C O 3 ) c ( F ) c 1 ) C ( = O ) O',
         b'C c 1 c c 